### PR TITLE
Force 1 second auto reload delay on all weapons

### PR DESCRIPTION
**Pull request by dave-sWpR46Ae**
Previously, when firing a shot, you had 1 second of free ammo to use however you wanted.  You can fire 2 stinger shots on quick aim with marksman and 10 ammo before you white reload currently.

I've fixed this with the following logic:

If 0 ammo, disable attack and wait 1 second.

If still 0 ammo, manually reload.

If 0 ammo and 0 magazines, say out of ammo and apply OOA debuff.

If reloading magazine is 3 or less, say low ammo.

Previously the wait 1 second was above the "If 0 ammo" statement, which means that it would wait 1 second after you attack to manually reload, so long as you used up all your ammo.  Guns that shoot faster than 1 second thus have a smaller window to reload, and they can get extra shots off if you wait for 1 ammo left.  Guns that shoot slower than 1 second are unaffected.  All weapons should wait exactly 1 second now.

### CODE REVIEW

**Comment by ReduxGelum** [comment]
The mistake in original code was a broken race condition, cos every attack fired a trigger, that did the reload stuff 1 second later. For example if I get down to 1 round, wait a bit, then fire up some skill that increases attack rate and shoot, ill have 1 second of free rounds. This can be quite significant on guns like laser, but is obviously energy inefficient to use in real games.

The new code is BROKEN too -- it disables the attack immediately, so if I try to fire with 1 round, i may not shoot at all if my attack speed is fast enough. Tested it with GPR, but obviously broken with laser or other fast-fire guns.

The correct fix is to repair the race condition, but I've no idea how to do it without introducing new bugs.
AP -- can u look at this and tell us what u think?

**Comment by ArcanePariah** [comment]
There really is not good solution in trigger, which is why in NOTD 2, reloading and ammo is almost entirely data driven.

**Comment by dave-sWpR46Ae** [comment]
If GPR doesn't work, no weapon will work.

You can split the wait to allow the attack to complete.  1 game second is a long time, but there's only a few bullets that could get through a 0.25 wait for example. we'd need to test every weapon.

Easy to test by dropping your mag down to 1 and attacking a barrel.  GPR works with a 0.25/0.75 wait, so you get 0.25 seconds of free ammo.

**Comment by ReduxGelum** [comment]
Good question whats more complicated -- adding a proper race condition or migrating to data?

**Comment by dave-sWpR46Ae** [comment]
How much does performance suffer from running a trigger every time you shoot?  I believe removing the "wait" from every shot is a good thing regardless of what we decide here, unless people want less time to manually reload on fast weapons.

Migrating to data is going to be a lot of work...

**Comment by ArcanePariah** [comment]
Data may be doable since it was all done fairly generically and is in a library/mod dependency

**Comment by dave-sWpR46Ae** [comment]
While I'm OK with migrating to data, it's simpler to do a dirty trigger fix (if everyone's okay with it).

I split the wait to 0.3 seconds and 0.7 seconds, which means you only get 0.3 seconds of free ammo (only useful on commando).  Stinger shoots at 0.26 but not at 0.25 second wait because of the damagepoint being 0.2 seconds.  Giving it some breathing room at 0.3.

I tested with virtually every weapon I could find and the sting was the only problem weapon at 0.25.  Never had it be an issue at higher than that.

**Pull request merged**
