### PR TITLE
Terrain updates

### PR DESCRIPTION
**Pull request by KithMeansFriend**
- Updated lighting sets for better aesthetic value.
- Liberally applied Lighting Regions and removed random Light doodads to improve map performance and increase aesthetic value.
- Generated Static Shadows.
- Re-painted custom pathing to simplify terrain cells and improve performance.
- Widened many terrain bridges and cliffs to improve performance and reduce chokepoints.
- Shuffled some doodad locations.
- Retrofitted Fort to something closer to its original form, making it highly defensible but featuring only a single exit.
- Removed the Armory Strip (tiny cliff north of Armory).
- Moved Ogilvy's Hut to the south end of Fort due to removing the Armory Strip.
- Deleted several destructible rocks that were no longer necessary.

### CODE REVIEW

**Comment by dave-sWpR46Ae** [comment]
Max FPS is about 70-75 for me on both terrain versions.  slightly lower fps in new fort, but I don't have a really good way to measure other than replays and time stamps.

**Comment by vgalbraith** [comment]
Seems like the highway to the island is a bit overkill, would making it the same size as the other 'bridges' still help with pathing calculations while fitting with the map better aesthetically?

**Comment by NiktosNOTD** [comment]
If you want to compare the terrains performance then simply do it in test mode. 
Disable usual triggers/ambient spawns, make yourself a trigger which spawns same amount of enemies in same spots, pick same class/skills go to spot you want to test, run trigger ->repeat for other terrain. Bonus points if your trigger includes message "finished spawning make screenshot".

Doing it by replays leaves your results to rng in too many aspects coz:
-what spawns where has impact, mob types behave differently in long travels
-distance mobs need to travel after spawning, 'random point' is just that sometimes it's middle of map sometimes corner
-rate at which you kill stuff off differs, i'd advise just not killing for test
-skills you have, periodic passives have higher impact that active on click skills ect

To make it realistic i wouldn't also spawn 500 zombois/agrons/something but say 5 groups of max 50 units per group of mixed types in distant spots and one near test spot

**Comment by KithMeansFriend** [comment]
Pull Request closed until I finish cleaning things up.

**Pull request closed without merging**
