### PR TITLE
Old models from NOTD

### PR DESCRIPTION
**Pull request by Xienus**
hi, i changed the Models of NOTD classes,

Commando > Warpig
FO > Raynor Sniper(old fo)
Medic > Marine
Marksman > Ghost
Rifleman> Raynor first campaign of sc1 wol(checked the marine is Black but does change to other colors)

and Tech > to Viking Merc( i Changed the Portrait as well (Thor) since it was the old notd one

I did this because everyone thinks old models were better than the ones blakq did, ( i like them too)

thanks.

### CODE REVIEW

**Comment by ReduxGelum** [comment]
Tested it and my comment is... NICE 

I think we need a little clarification on this. Blaqk worked hard on downloading the models from sc2mapster, and when i saw the new SMM I liked it. But I also saw multiple community members wishing the old models to be returned, so I assume Blaqk sort of forced this change. Personally I don't mind the old ones, aside from the fact I want medic to use medic model, like in ancient versions.

**Comment by ReduxGelum** [comment]
I think you should open a forum thread, and obviously we can have a temporary change like my initial idea with gravgun.

**Comment by dave-sWpR46Ae** [comment]
I'll have to test, but I disapprove of any change to tech.  No reason for cmd to have anything other than warpig IMO, but the warhound was almost made for technician, and robomonkey's portraits were made for the warhound.  It's a step backwards to revert.

**Comment by ReduxGelum** [comment]
This really isn't accurate rockz. Someone just saw warhound in swarm beta and said "hey this would be a cool thing to use for tech". While I don't mind either model, I'll point out the new one is in no way an improvement. Its just different style.

Robomonkeys art is also not an argument for the model. I liked the art cos its much better than that old icon that was very out of place. Not cos it fits the tech model or something.

**Comment by dave-sWpR46Ae** [comment]
That someone being kithrixx.

I will say this: the warhound fits the technician better than hel's angel ever did.  It's a janky ass walker that looks like it was thrown together.

Additionally, while the new portraits work perfectly, they never updated the class selection screen from hel's angel.

**Comment by dave-sWpR46Ae** [comment]
You added the bin map, not the src map updates.  You'll need to remove the "merge from remote fork" commit.

**Pull request merged**
