### PR TITLE
Removes the wait 0.7 that I added in somehow.  This was causing the s…

### PR DESCRIPTION
**Pull request by dave-sWpR46Ae**
…tinger to wait 0.7 seconds after being under 10 rounds to disable the attack button, which would cause you to have a permanently disabled attack button after reload if you reloaded fast enough.

This is only one line and can be changed easily I think, unlike the previous fix which changed a TON of lines of code for a one line fix.  It would still be better to revert https://github.com/ArcanePariah/Night-of-the-Dead/commit/418820f6434dfdbc94d608733c4118ac3d1e259a and reapply the fixes afterwards as I believe it also made unintended changes to the FO fix.

### CODE REVIEW

**Comment by ThunderRazor** [comment]
How does this guarantee that my stinger will not be bugged?
How does this prevent 10 ammo from disappearing when the missile was never fired? because that happens plentifully without any reload bugs.
Please check out the fix I have as it solves more problems than just a reload bug.
Granted, my fix has more lines of code (I would not say a TON since a TON is 1000 kg), but the patch I made fixes a more fundamental problem: **consuming ammo before the missile is fired.** Unlike GPR, Barret, SG, and other bullet weapons, the stinger actually creates a missile unit and is not instantaneous.

Also, I don't see how the stinger 0.7-second delay has anything to do with the forward observer unless you're talking about a revert 418820f causing unintended changes to FO?? I'm a little confused about this part. Nevermind! I think I understand the FO thing.

**Comment by dave-sWpR46Ae** [comment]
Correct, I have a lot of changes in https://github.com/ArcanePariah/Night-of-the-Dead/commit/418820f6434dfdbc94d608733c4118ac3d1e259a that refer to the FO.  I don't understand why they are there, and I don't know enough about the FO triggers/changes to know if anything broke.

This would be the quick fix (it's a one line deletion) and could be added without serious review.  Your fix changes something different and likely does the same thing this does, plus a much needed other fix.  I have not reviewed it yet.  This is mainly a test to make sure that I can do git properly without major issues.  Next time I will wait to submit fixes until I have a more recent master to call from, as one of the patches that Blizzard made a bunch of changes to the code.

If/when https://github.com/ArcanePariah/Night-of-the-Dead/pull/187 is added then this can be closed.

**Comment by ThunderRazor** [comment]
AP mentioned that he had to resolve some conflicts when he was merging FO fixes and asked me to check to make sure the FO still worked. The current version includes the proper FO fixes and I already verified this. To my understanding, if you're worried that 418802f already caused problems, those problems have already been resolved. When you said "revert 418802f",  I'm under the impression you mean to "undo" the changes made by 418802f?

**Comment by dave-sWpR46Ae** [comment]
Yes.  If there are no issues with FO, then it's fine and we can leave https://github.com/ArcanePariah/Night-of-the-Dead/commit/418820f6434dfdbc94d608733c4118ac3d1e259a in place.

**Comment by ArcanePariah** [comment]
If I'm understanding these pull requests, this pull is covered by #187?

**Comment by dave-sWpR46Ae** [comment]
Correct.  If you merge #187 then close this one.

**Comment by dave-sWpR46Ae** [comment]
Thunder's version is perfect.  Closing.

**Pull request closed without merging**
