### PR TITLE
Minor Tweak to Improve Siege Timing

### PR DESCRIPTION
**Pull request by ThunderRazor**
Additional Notes:
~ Added a Motion Detector to Marines during Reinforcements to improve the Siege Timing.
~ Motion Detector tells the Tanks when the Marines are moving or standing still.
~ Motion Detector is a Hidden Behavior named "Not Moving" which is disabled while the Marine is moving.
~ Replaces the "goal position" condition that previously dictated Siege Timing.
~ "Goal position" previously included the Marine's weapon target position, thus Tanks often unsieged when the Escort Marine is shooting.

### CODE REVIEW

**Comment by ThunderRazor** [comment]
I created a very simple passive behavior in the data editor; added and swapped a couple lines of code in the trigger editor (charlie company ai). Not sure why it would create such a large diff.
Redid the changes from scratch again in a new branch; the diff size is about the same.
The only difference between the two versions is that in the 2nd version, I replaced lines rather than added new and deleted old. (+9264/-9233 versus +9287/-9249)

**Comment by ArcanePariah** [comment]
Did you merge master into your branch first? If not, the diff is presenting the changes you have from master, which may be quite a bit given the merges I've made to it. Also, the triggers.xml having large changes is normal.

**Comment by ThunderRazor** [comment]
The primary source of diff seems to be coming from the PreloadAssetDB.txt file (about +9178/-9173).
All of which are deletions of "swarm.m" data, and additions of "void.m" data.
Maybe the fact that I recently purchased the collectors version of Void has something to do with it?
I get about the same diff with other branch commits.
And yes, my master is even with your master. I did this before any of the latest commits/pull requests.

**Comment by ArcanePariah** [comment]
That would do it.

**Comment by ThunderRazor** [comment]
The editor is attempting to replace swarm assets with void assets?
Are you able to merge the changes I made without the changes to PreloadAssetDB.txt?

**Pull request merged**
