### PR TITLE
Add automatic ban conditions - Please test

### PR DESCRIPTION
**Pull request by dave-sWpR46Ae**
Lets try this again.

Adds illegal conditions focused primarily on wins.

### CODE REVIEW

**Comment by ReduxGelum** [comment]
I've reviewed the changes and currently am in some brainstorming about what can be done about this. But not to forget remarks:

else if ((gv_playerXP[lp_player] > ((gv_eCSpeed[lp_player] * 237) + (gv_eCWinNormal[lp_player] * 207) + (gv_eCNMSpeed[lp_player] * 274) + (gv_eCWinNM[lp_player] * 234) + (gv_aCSpeed[lp_player] * 260) + (gv_aCWinNormal[lp_player] * 230) + (gv_aCNMSpeed[lp_player] * 305) + (gv_aCWinNM[lp_player] * 265) + (gv_sTSpeed[lp_player] * 308) + (gv_sTWinNormal[lp_player] * 278) + (gv_sTNMSpeed[lp_player] * 408) + (gv_sTWinNM[lp_player] * 368) + (gv_survivalWin[lp_player] * 267) + (gv_survivalWinNM[lp_player] * 367) + ((gv_playerGamesPlayed[lp_player] - (gv_eCSpeed[lp_player] + gv_eCWinNormal[lp_player] + gv_eCNMSpeed[lp_player] + gv_eCWinNM[lp_player] + gv_aCSpeed[lp_player] + gv_aCWinNormal[lp_player] + gv_aCNMSpeed[lp_player] + gv_aCWinNM[lp_player] + gv_sTSpeed[lp_player] + gv_sTWinNormal[lp_player] + gv_sTNMSpeed[lp_player] + gv_sTWinNM[lp_player] + gv_survivalWin[lp_player] + gv_survivalWinNM[lp_player])) * 280)))) {

else if ((gv_playerXP[lp_player] < ((gv_eCSpeed[lp_player] * 55) + (gv_eCWinNormal[lp_player] * 45) + (gv_eCNMSpeed[lp_player] * 134) + (gv_eCWinNM[lp_player] * 94) + (gv_aCSpeed[lp_player] * 132) + (gv_aCWinNormal[lp_player] * 102) + (gv_aCNMSpeed[lp_player] * 187) + (gv_aCWinNM[lp_player] * 147) + (gv_sTSpeed[lp_player] * 129) + (gv_sTWinNormal[lp_player] * 99) + (gv_sTNMSpeed[lp_player] * 194) + (gv_sTWinNM[lp_player] * 154) + (gv_survivalWin[lp_player] * 202) + (gv_survivalWinNM[lp_player] * 287) + ((gv_playerGamesPlayed[lp_player] - (gv_eCSpeed[lp_player] + gv_eCWinNormal[lp_player] + gv_eCNMSpeed[lp_player] + gv_eCWinNM[lp_player] + gv_aCSpeed[lp_player] + gv_aCWinNormal[lp_player] + gv_aCNMSpeed[lp_player] + gv_aCWinNM[lp_player] + gv_sTSpeed[lp_player] + gv_sTWinNormal[lp_player] + gv_sTNMSpeed[lp_player] + gv_sTWinNM[lp_player] + gv_survivalWin[lp_player] + gv_survivalWinNM[lp_player])) * 1)))) {

else if (((MaxI((gv_silverStar[lp_player] - 20), 0) + MaxI((gv_lifeSavingMedal[lp_player] - 20), 0)) > (gv_eCNMSpeed[lp_player] + gv_eCWinNM[lp_player] + gv_aCNMSpeed[lp_player] + gv_aCWinNM[lp_player] + gv_sTNMSpeed[lp_player] + gv_sTWinNM[lp_player] + gv_survivalWinNM[lp_player]))) {

else if ((gv_medalOfHonor[lp_player] > (gv_eCNMSpeed[lp_player] + gv_eCWinNM[lp_player] + gv_aCNMSpeed[lp_player] + gv_aCWinNM[lp_player] + gv_sTNMSpeed[lp_player] + gv_sTWinNM[lp_player] + gv_survivalWinNM[lp_player]))) {

else if ((gv_combatActionRibbon[lp_player] < (gv_eCSpeed[lp_player] + gv_eCWinNormal[lp_player] + gv_eCNMSpeed[lp_player] + gv_eCWinNM[lp_player] + gv_aCSpeed[lp_player] + gv_aCWinNormal[lp_player] + gv_aCNMSpeed[lp_player] + gv_aCWinNM[lp_player] + gv_sTSpeed[lp_player] + gv_sTWinNormal[lp_player] + gv_sTNMSpeed[lp_player] + gv_sTWinNM[lp_player] + gv_survivalWin[lp_player] + gv_survivalWinNM[lp_player]))) {

This will affect old bankfile players (not bad but undesired)
Check are also overcomplicated and easily avoidable (so pointless).

**Comment by ReduxGelum** [comment]
The rest of the changes are more or less needed by this long-neglected function.

**Comment by dave-sWpR46Ae** [comment]
None of the checks are complicated at all.  Also it won't affect old banks.  Wins were tracked after Combat Action Ribbons.  Otherwise I could make CAR = Wins.

**Comment by ReduxGelum** [comment]
Conditions with 15 hard coded numbers for XP checks aren't complicated? Cos it looks overcomplicated to me, especially considering that the person who is going to multiply his existing ec wins by 1000 will easily bypass this with next to no effort. Which raises a question whats the point? The average check catches idiots who just add xp without wins already.

I said this before and Ill repeat myself - there is no error in the condition, its the assumption that the condition is more useful than a basic 1 condition if-then check that's wrong. 

As for old banks -- there's approximately ~40k xp deviation according to squish that you don't take into account. And I've no idea whats the deviation on medals. So I wouldn't be so hasty adding such rigorous checks in an area that we both know is never going to be rigorous enough to find even the slighly-above average hackers.

If you want these conditions in codebase, fine, they aren't wrong. You are simply overdoing in area where a much simpler check solves most of the problems.

**Comment by dave-sWpR46Ae** [comment]
This will ban ReduxGelum as he has 1 more win than combat action ribbon.  Not sure how he pulled this off.

**Comment by ReduxGelum** [comment]
Hacker! 

Seriously though its on my bank since ~30k. Jm has the same thing, and multiple other players. Maybe u get it at first game?

**Comment by dave-sWpR46Ae** [comment]
I threw out all the other checks and tested each individual check.  I did find some faulty logic for the survival wins, but that works as expected now (each surv win needs a SS medal to go with it, so if you have less SS medals than surv wins, you hacked).  To test locally, you have to modify the "SetDifficulty" function to trigger on test maps and disable the custom ban list.

Without a program to decode all of my backup banks to find out exactly which game I gained wins without gaining a CAR, I don't think we can debug the wins vs CAR fiasco, and even then, it's unlikely we will be able to use it in a future patch due to the banks that have all been corrupted due to an unknown bug.

The most important thing is preventing people from having negative stats and weapon mods, which gives them an absolutely unfair advantage without also taking an additional 400% damage.

If I need to rewrite this because it's too old, I can.

**Review by ReduxGelum — COMMENTED** [review]
Works for my bank, recommend publishing a private version, and inviting players into it (they need to copy their bank to correct folder for this)

Code is much cleaner than previous version.

My guess is this will still not fix the hacked bank with +4 in every wepmod, right?

**Comment by dave-sWpR46Ae** [comment]
This fixes +4 in all mods.  You can never have negative available weapon mods.  7*5=35, and 5 is a "zero" on the weapon mod charts, with 1 being -4 and 9 being +4.  The sum can never exceed 35 legitimately.

+    else if (((gv_statsModProperties[1][lp_player] + gv_statsModProperties[2][lp_player] + gv_statsModProperties[3][lp_player] + gv_statsModProperties[4][lp_player] + gv_statsModProperties[5][lp_player] + gv_statsModProperties[6][lp_player] + gv_statsModProperties[7][lp_player]) > 35)) {

This fixes +9 in all stats.  You can never have +9 in all stats anyway because of the 600k limit.

+    else if ((((gv_playerRank[lp_player] * 2) + gf_GetMedalStats(lp_player)) < gf_GetCurrentAllocatedStats(lp_player))) {

This is just generic BS, easily bypassable by a competent hacker, but it doesn't harm anything to leave it in.

+    else if ((gf_StatsGetMaxModPoints(lp_player) < gv_modTotalPointsNegative[lp_player])) {

**Pull request merged**
