### PR TITLE
Kith's XP Rework (NOT FINISHED YET LOL)

### PR DESCRIPTION
**Pull request by KithMeansFriend**
Removed fractional XP rewards from all enemies via removal of the SharedExperience behavior.
Allowed Classes to share experience via removal of the xpsharing effect from CriticalStrikesAttacker behavior.
Allowed the X-1 and Reaper Drone to share experience via removal of XPShareSuppression.
Enabled full/global XP share from classes via updating the Basic_Hero Behavior.
Updated Kill XP values for all units.

### CODE REVIEW

**Comment by dave-sWpR46Ae** [comment]
Parasites and banelings still have BehaviorArray Link="SharedExperience".

Terrain was changed?

Probably would be good to separate the changes into 2 separate pulls:
1) functioning share removal
2) XP changes

**Comment by KithMeansFriend** [comment]
re: Parasites and Banelings, fixed. I don't know why those got skipped. Loading problems, maybe.

re: Terrain, I must've accidentally touched something when I was looking at the Pathing. Whatever it is, it can be safely discarded.

As for the functional share removal vs XP changes, the leveling rate would take a _drastic_ downturn if not for the XP bumps, especially in the case of things like Ghouls. The current Ghoul can potentially award up to 7 XP total with the right team composition, so that needs to be accounted for.

**Comment by dave-sWpR46Ae** [comment]
Splitting it up just means each pull does less, making it easier to see what each thing does.

Also global share on recon is radius 500.  Not sure how it relates to the map (not sure how big the map actually is).

**Comment by NiktosNOTD** [comment]
The 300 range is on me.
Math is hard after all, map is 256x256 so just tossed 300 quickly without thinking. 375 will be greater than longest diagonal distance posible(~363). But just setting it to anything bigger should not have 'much' impact on anything if any impact at all

**Comment by KithMeansFriend** [comment]
Good news: I have increased the share range to 400 so there's no possible way it can screw up.

**Comment by dave-sWpR46Ae** [comment]
You removed XP from InfestorTerran2 and ZombieBroodMother.  This is why I want you to be more careful and separate your changes into 2 commits, so we don't mess things up and let stupid crap through.  I'm speaking from experience here because I literally just did this (though I blame blizzard on the most recent issue).  Get a working system first, prove it functions.  Don't touch XP while you're doing this.  As far as I'm concerned these are two separate issues and you should treat them as such.  

Then go in and categorize every unit (make a list of what their current values are) and figure out a flat modifier to increase XP by to balance and make a post on the forums detailing this so we have the information.  Once you balance the gameplay out we'll already have an XP list started that you can modify later.

At this point you should just close the pull request and start over (don't submit the pull request until it's ready to be merged or looked at by other people).

**Comment by KithMeansFriend** [comment]
Both the BroodMother and the Infestor have KillXP values - 30 and 40, respectively. I'm not sure what you're talking about.

**Comment by dave-sWpR46Ae** [comment]
They have been reverted to the default blizzard number and thus they are completely deleted.  If blizzard changes these values ever, we're at their mercy.  That's why they're blue in the editor and they don't exist in unitdata.xml anymore.

Perhaps it would be better to reorganize units first into data so we don't get screwed over like we did with agrons.

**Comment by KithMeansFriend** [comment]
There's a lot that we're at the mercy of Blizzard with, mostly because NOTD was not planned very well (if at all). I have no problem with reorganizing the units to make them less susceptible to unintended changes, but that's outside the scope of the XP Rework and therefore not my concern at this time.

**Comment by dave-sWpR46Ae** [comment]
Ran a test game.  Predator gets 0 XP share when far from team.  Players that are far from team get much less XP.  The XP difference is around 5500 kills is around 1000 xp for recon running around.

Egg bug is caused by new SC2 map.

L3 doesn't share.  Global share appears to be gone, but appears to be there at the same time.

**Comment by KithMeansFriend** [comment]
Pull request closed for now until such time that I finish cleaning things up.

**Pull request closed without merging**
