### PR TITLE
Civilian rescue disabled until airlock battle is over

### PR DESCRIPTION
**Pull request by ReduxGelum**
A common problem in pubs is that newbies just step on the hexes without thinking. BBQ hex was supposed to solve this by punishing uncoordinated newbies with death, but that works only on vet/nm.

Civilian hexes premature trigger is a common problem in pubs as a result, so added an extra requirement for objective to complete before bonus can be activated.

PATCH NOTES:
Delta-1 civilian rescue disabled until airlock battle is over

### CODE REVIEW

**Comment by ArcanePariah** [comment]
Do you differentiate between newbie and vet/NM for doing this? Or is there an alternative trigger for that. If my memory serves, in Vet/NM the Delta Civs HAVE to be rescued prior to the airlock waves completing.

**Comment by ReduxGelum** [comment]
No, there is no difference between vet/nm and recruit, and there should be none.

In recruit main problem is EXACTLY the premature trigger during airlock battle, which causes frustration.
In non-recruit players either don't trigger civs at all or do them same way as recruit, just to be safe, cos they die to way too many hulks that spawn on high sq otherwise.

**Comment by NiktosNOTD** [comment]
What arcane means is how in non-recruit civs simply spawn as seekers/zombies if you wait for airlock mission to properly complete (it's in "wave 5- airlock battle" trigger). 
If you lock civs behind completing airlock defense then you guarantee 0 civs will spawn in non recruit. [that might be different depending if your stuff checks for airlock battle being 'completed' as in tick shows up as done, or 'completed' as objective replaced by new one]

**Comment by ReduxGelum** [comment]
Look at the trigger you mentioned, "Wave 5 - Airlock Battle". 
There is a 25 second wait period (real time) between objective marked as complete, and civ trigger being swapped.
This is where I added the gate for civ activation. 

Also, now that I looked at it again, I remembered that I once wanted to add a bonus objective that is displayed at this time, like "Check delta-1 for survivors". Ill add this, yet another minor improvement for recruit.

**Comment by ReduxGelum** [comment]
Do we have questions regarding this change or not?

**Pull request merged**
